#!/usr/bin/env python3
"""
Twemoji Icon Downloader & Converter

Downloads specific emoji from Twitter's Twemoji project and converts them
to 32x32 JSON icon format for MatrixOS. No runtime dependencies needed!

Twemoji License: CC-BY 4.0 & MIT (compatible with this project)
Source: https://github.com/twitter/twemoji
"""

import urllib.request
import json
import sys
import os

# Add PIL import
try:
    from PIL import Image
    import io
except ImportError:
    print("Error: Pillow required for this tool only (not for runtime!)")
    print("Install with: sudo apt-get install python3-pil")
    sys.exit(1)


def emoji_to_codepoint(emoji):
    """Convert emoji character to Unicode codepoint string.
    
    Example: 🕹️ -> '1f579-fe0f'
    """
    # Get codepoints for each character
    codepoints = []
    for char in emoji:
        cp = ord(char)
        # Skip variation selectors that twemoji doesn't use in filenames
        if cp == 0xFE0F:  # Emoji presentation selector
            continue
        codepoints.append(f"{cp:x}")
    
    return '-'.join(codepoints)


def download_twemoji(emoji, size=72):
    """Download emoji PNG from Twemoji CDN.
    
    Args:
        emoji: Emoji character (e.g., "🕹️")
        size: Source size (72 or 36)
    
    Returns:
        PIL Image object or None if failed
    """
    codepoint = emoji_to_codepoint(emoji)
    url = f"https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/{size}x{size}/{codepoint}.png"
    
    print(f"Downloading {emoji} from {url}...")
    
    try:
        with urllib.request.urlopen(url, timeout=10) as response:
            img_data = response.read()
            img = Image.open(io.BytesIO(img_data))
            return img
    except Exception as e:
        print(f"  ❌ Failed: {e}")
        return None


def image_to_icon_json(img, output_size=32):
    """Convert PIL Image to icon.json format.
    
    Args:
        img: PIL Image
        output_size: Target size (16 or 32)
    
    Returns:
        Dictionary suitable for icon.json
    """
    # Resize to target size with high quality
    img = img.resize((output_size, output_size), Image.Resampling.LANCZOS)
    
    # Convert to RGBA if not already
    img = img.convert('RGBA')
    
    # Extract pixel data
    pixels = []
    for y in range(output_size):
        row = []
        for x in range(output_size):
            r, g, b, a = img.getpixel((x, y))
            # If mostly transparent, use None (will be rendered as transparent)
            if a < 128:
                row.append(None)
            else:
                row.append([r, g, b])
        pixels.append(row)
    
    return {
        "format": "rgb",
        "pixels": pixels,
        "source": "Twemoji (Twitter) - CC-BY 4.0",
        "note": "Generated by twemoji_downloader.py"
    }


def save_emoji_icon(emoji, name, output_dir='matrixos/emoji_icons', sizes=[32]):
    """Download emoji and save as icon JSON files.
    
    Args:
        emoji: Emoji character
        name: Filename (without extension)
        output_dir: Directory to save to
        sizes: List of sizes to generate (16, 32)
    """
    # Download from Twemoji (72x72 source)
    img = download_twemoji(emoji, size=72)
    
    if img is None:
        return False
    
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Generate each size
    for size in sizes:
        icon_data = image_to_icon_json(img, size)
        filename = os.path.join(output_dir, f"{name}_{size}.json")
        
        with open(filename, 'w') as f:
            json.dump(icon_data, f, indent=2)
        
        print(f"  ✅ Saved {size}×{size} to {filename}")
    
    return True


def batch_download_common_emojis(output_dir='matrixos/emoji_icons'):
    """Download a curated set of common emojis useful for MatrixOS apps."""
    
    common_emojis = {
        # Gaming & Entertainment
        'joystick': '🕹️',
        'gamepad': '🎮',
        'alien': '👾',
        'dice': '🎲',
        'slot': '🎰',
        
        # Animals & Nature
        'snake': '🐍',
        'frog': '🐸',
        'ghost': '👻',
        'fire': '🔥',
        'star': '⭐',
        'sparkles': '✨',
        
        # Objects
        'brick': '🧱',
        'paddle': '🏓',
        'clock': '⏰',
        'watch': '⌚',
        'calendar': '📅',
        'chart': '📊',
        'graph': '📈',
        
        # Weather
        'sun': '☀️',
        'cloud': '☁️',
        'rain': '🌧️',
        'thunder': '⛈️',
        'snow': '❄️',
        'rainbow': '🌈',
        
        # Tech & Symbols
        'wifi': '📶',
        'battery': '🔋',
        'gear': '⚙️',
        'warning': '⚠️',
        'check': '✅',
        'cross': '❌',
        'music': '🎵',
        'speaker': '🔊',
        
        # UI Elements
        'play': '▶️',
        'pause': '⏸️',
        'stop': '⏹️',
        'info': 'ℹ️',
        'question': '❓',
        'home': '🏠',
    }
    
    print("\n" + "="*60)
    print("Downloading Common Emoji Icons")
    print("="*60 + "\n")
    
    success_count = 0
    fail_count = 0
    
    for name, emoji in common_emojis.items():
        if save_emoji_icon(emoji, name, output_dir, sizes=[16, 32]):
            success_count += 1
        else:
            fail_count += 1
    
    print("\n" + "="*60)
    print(f"✅ Successfully downloaded: {success_count}")
    print(f"❌ Failed: {fail_count}")
    print(f"📁 Saved to: {output_dir}/")
    print("="*60 + "\n")


def create_emoji_manifest(output_dir='matrixos/emoji_icons'):
    """Create a manifest.json mapping emoji names to characters."""
    
    # Scan directory for emoji files
    manifest = {}
    
    if not os.path.exists(output_dir):
        return
    
    for filename in os.listdir(output_dir):
        if filename.endswith('_32.json'):
            name = filename.replace('_32.json', '')
            # Try to load and extract source emoji
            filepath = os.path.join(output_dir, filename)
            try:
                with open(filepath, 'r') as f:
                    data = json.load(f)
                    # For now just note that it exists
                    manifest[name] = {
                        "sizes": [16, 32] if os.path.exists(os.path.join(output_dir, f"{name}_16.json")) else [32],
                        "source": "twemoji"
                    }
            except:
                pass
    
    manifest_path = os.path.join(output_dir, 'manifest.json')
    with open(manifest_path, 'w') as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
    
    print(f"📄 Created manifest: {manifest_path}")


if __name__ == '__main__':
    if len(sys.argv) > 1:
        # Download specific emoji
        emoji = sys.argv[1]
        name = sys.argv[2] if len(sys.argv) > 2 else 'emoji'
        save_emoji_icon(emoji, name)
    else:
        # Download common set
        batch_download_common_emojis()
        create_emoji_manifest()
    
    print("\n💡 Usage in config.json:")
    print('  "icon": "joystick"  → Loads from emoji_icons/joystick_32.json')
    print('  "icon": "🕹️"         → Downloads on first use (requires font)')
    print('  "icon": "icon.json"  → Custom hand-drawn icon\n')
